# Telegram Bot Configuration
# To get these values:
# 1. Create a bot with @BotFather on Telegram
# 2. Get your BOT_TOKEN from @BotFather
# 3. Get your CHAT_ID by sending a message to your bot and visiting:
#    https://api.telegram.org/bot<BOT_TOKEN>/getUpdates

BOT_TOKEN = "your_telegram_bot_token_here"
CHAT_ID = "your_telegram_chat_id_here"

# Example (replace with actual values):
# BOT_TOKEN = "1234567890:ABCdefGHIjklMNOpqrsTUVwxyz"
# CHAT_ID = "987654321"